import test from'node:test';import assert from'node:assert/strict';import{parseJson,formatJson,minifyJson,encodeBase64,decodeBase64,encodeUrl,decodeUrl,generatePassword,passwordStrength,countText,convertCase,parseHex,rgbToHex,rgbToHsl,hslToRgb,contrastRatio,timestampToDate,dateToTimestamp}from'../public/assets/utility-core.js';
test('JSON formats, sorts, minifies and reports position',()=>{assert.equal(formatJson('{"b":1,"a":2}',{sortKeys:true}),'{\n  "a": 2,\n  "b": 1\n}');assert.equal(minifyJson(' { "a": 1 } '),'{"a":1}');const r=parseJson('{\n"a": }');assert.equal(r.valid,false);assert.ok(r.error)});
test('Base64 round trips Unicode',()=>{const s='Hello, తెలుగు 👋';assert.equal(decodeBase64(encodeBase64(s)),s);assert.throws(()=>decodeBase64('%%%'))});
test('URL modes round trip',()=>{const s='a/b?x=hello world&emoji=✓';assert.equal(decodeUrl(encodeUrl(s,'component'),'component'),s);assert.equal(decodeUrl(encodeUrl('https://x.test/a b?q=1','full'),'full'),'https://x.test/a b?q=1')});
test('password includes enabled sets deterministically',()=>{const p=generatePassword({length:20},n=>Uint32Array.from({length:n},(_,i)=>i*17+3));assert.equal(p.length,20);assert.match(p,/[a-z]/);assert.match(p,/[A-Z]/);assert.match(p,/\d/);assert.match(p,/[^A-Za-z0-9]/);assert.ok(passwordStrength(p).entropy>80)});
test('word statistics support Unicode and paragraphs',()=>{const c=countText('Hello world.\n\nనమస్కారం ప్రపంచం!');assert.equal(c.words,4);assert.equal(c.paragraphs,2);assert.equal(c.sentences,2);assert.ok(c.characters>c.charactersNoSpaces)});
test('case converter covers developer cases',()=>{assert.equal(convertCase('hello JSON world','snake'),'hello_json_world');assert.equal(convertCase('hello world','camel'),'helloWorld');assert.equal(convertCase('hello world','pascal'),'HelloWorld');assert.equal(convertCase('hello world','constant'),'HELLO_WORLD')});
test('color conversion round trips and checks contrast',()=>{const rgb=parseHex('#2783DE');assert.equal(rgbToHex(rgb),'#2783DE');const back=hslToRgb(rgbToHsl(rgb));assert.deepEqual({r:back.r,g:back.g,b:back.b},{r:39,g:131,b:222});assert.ok(contrastRatio(parseHex('#000'),parseHex('#fff'))>20)});
test('timestamp seconds and milliseconds are detected',()=>{assert.equal(timestampToDate(0).toISOString(),'1970-01-01T00:00:00.000Z');assert.equal(timestampToDate(1700000000000).getTime(),1700000000000);assert.equal(dateToTimestamp(new Date('2024-01-01T00:00:00Z')),1704067200)});
