import {access,readFile,readdir} from 'node:fs/promises';
import {tools,legal} from '../src/tools.mjs';

const exists=path=>access(path).then(()=>true,()=>false);
const htmlFiles=[];
const walkHtml=async dir=>{
 for(const entry of await readdir(dir,{withFileTypes:true})){
  const path=`${dir}/${entry.name}`;
  if(entry.isDirectory())await walkHtml(path);
  else if(path.endsWith('.html'))htmlFiles.push(path);
 }
};
const routeFile=pathname=>pathname==='/'?'dist/index.html':pathname.endsWith('/')?`dist${pathname}index.html`:`dist${pathname}`;
const expectedRoutes=['/','/tools/',...tools.map(tool=>`/tools/${tool.slug}/`),...legal.map(([slug])=>`/${slug}/`)];
for(const route of expectedRoutes)if(!await exists(routeFile(route)))throw new Error(`Missing generated route: ${route}`);

const overrideSource=await readFile('scripts/overrides.mjs','utf8');
for(const tool of tools){
 if(tool.slug==='pdf-editor')continue;
 if(!overrideSource.includes(`'${tool.slug}'`))throw new Error(`Upgraded route is not generated by overrides.mjs: ${tool.slug}`);
}

await walkHtml('dist');
const broken=[];
for(const file of htmlFiles){
 const html=await readFile(file,'utf8');
 for(const match of html.matchAll(/(?:href|src)=["'](\/[^"'#?]*)/g)){
  const url=match[1];
  const target=url==='/'?'dist/index.html':url.endsWith('/')?`dist${url}index.html`:`dist${url}`;
  if(!await exists(target))broken.push(`${file} -> ${url}`);
 }
}
if(broken.length)throw new Error(`Broken local links/assets:\n${broken.join('\n')}`);
console.log(`QA passed for ${expectedRoutes.length} routes and ${htmlFiles.length} HTML files`);
